### ISSUE TITLE
TypeError for Run_gtAI.gtai_analysis

### ISSUE THREAD

**Issue by shenweiyan** [AliYoussef96/gtAI#1]
The `gtai_analysis` function in `gtAI/Run_gtAI.py` has the parameter order fixed, but the README incorrectly lists the parameters in a different order. As a result, if users follow the instructions in the README to execute the program, errors may occur. It is requested to fix this issue by updating the README file to reflect the correct parameter order and ensure that users can execute the program successfully.

**Comment by AliYoussef96** [comment]
Hi @shenweiyan, I appreciate you bringing up this concern! I have made the necessary changes to the README file, and it now accurately represents the correct order of parameters.

```python
Run_gtAI.gtai_analysis(main_fasta = main_fasta, GtRNA = GtRNA , ref_fasta = ref_fasta, genetic_code_number = genetic_code_number, size_pop=size_pop, generation_number=generation_number, bacteria=bacteria )
                                                      
```
