### ISSUE TITLE
df.drop issue

### ISSUE THREAD

**Issue by SouradiptoC** [AliYoussef96/gtAI#2]
while working with `RSCU_calc`, the following error came up

`df.drop(['ATG'],0,inplace= True)`
`TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given`

This is happening because of line no 59 in `CA_RSCU.py`, where you've used `df.drop(['ATG'],0,inplace= True)`. It should be `df.drop(['ATG'],axis=0,inplace= True)`.

If you can rectify the problem and release a new version, then that will be helpful

**Comment by AliYoussef96** [comment]
Hi @SouradiptoC, I appreciate you bringing up this concern! I fixed the line in GitHub version, and I will work to release a new PyPI version as soon as possible.

https://github.com/AliYoussef96/gtAI/blob/0d5b21fe4c678a9c6834b89d3065431bb1042879/gtAI/CA_RSCU.py#L59

**Comment by AliYoussef96** [comment]
Hi @SouradiptoC a new version has been released on PyPI, gtAI 1.0.5 .

https://pypi.org/project/gtAI/
